### ISSUE TITLE
Tłumaczenia

### ISSUE THREAD

**Issue by ad-m** [ad-m/mc-theme#1]
Jak efektywnie generować pliki *.pot?

**Comment by ad-m** [comment]
Należy także zastąpić polskie literały angielskimi odpowiednikami w właściwy sposób. Theme Check zgłasza: 
> INFO: Non-printable characters were found in the page-home.php file. You may want to check this file for errors.
> 
> Line 17: <div class='header__subtitle'>Dost��pne jest <a href='<?php echo get_post_type_archive_link('post'); ?>'>arch
> 
> INFO: Non-printable characters were found in the header.php file. You may want to check this file for errors.
> 
> Line 33: <p class='top-bar__welcome'>Przejd�� do <a href='mc.gov.pl/cyfryzacja'>g��ównego serwisu Ministerstwa Cyfryz
> 
> INFO: Non-printable characters were found in the footer.php file. You may want to check this file for errors.
> 
> Line 21: <p>To jest miejsce do mniej formalnej komunikacji, wymiany do��wiadcze�� oraz udostępnienia tych rzeczy, które
> 
> Line 22: dla Pa��stwa mogą być istotne i ciekawe.</p>
> 
> Line 26: <h1 class='header__title'>Znajd�� nas</h1>
> 
> Line 28: <p>Adres<br> Królewska 27<br> 00-500 Warszawa<br></p>
> 
> Line 29: <p>Godziny<br>Poniedzia��ek—piątek: 8:15–16:15</p>
> 
> Line 37: Przejd�� do strony Biuletynu Informacji Publicznej Ministerstwa Cyfryzacji
> 
> Line 41: <p>Artyku��y zamieszczone w serwisie GOV.PL, w których nie podajemy ��adnych dodatk
> 
> Line 42: praw autorskich, nale��ą do informacji publicznych i udostępniamy je bezp��atnie. Korzystanie 
> 
> Line 43: niezale��nie od celu i sposobu korzystania, nie wymaga zgody Ministerstwa. Dostęp
> 
> Line 54: printf(esc_html__('Theme: %1$s by %2$s.', 'mc_theme'), 'mc_theme', '<a href='https://facebook.com/adam.dobrawy'>Karol Bregu��a & Kamil Bregu��a</a>');

**Comment by ad-m** [comment]
Grunt w mojej konfiguracji ?

**Comment by mik-laj** [comment]
Ja ręcznie sobie wykonuje skrypt PHP, bo nigdy be mam czasu, aby zgrać go z gulpem.

**Comment by ad-m** [comment]
```
svn export http://i18n.svn.wordpress.org/tools/trunk/
....
wp-makepot wp-theme /home/adas/Devel/mc-blog/wp-content/themes/mc_theme /home/adas/Devel/mc-blog/wp-content/themes/mc_theme/languages/mc_theme.pot
poedit mc_theme.pot; # Save as -> pl_PL.po
wp-makepot wp-theme /home/adas/Devel/mc-blog/wp-content/themes/mc_theme /home/adas/Devel/mc-blog/wp-content/themes/mc_theme/languages/mc_theme.pot
poedit pl_PL.pot; # Import from mc_theme.pot
```

**Comment by ad-m** [comment]
```bash
git pull origin l10n_master 
for file in `find . -name "*.po"` ; do msgfmt -o ${file/.po/.mo} $file ; done
git commit -a -m "Update translation" -a;
git push origin;
```
