### ISSUE TITLE
Naprawienie wykazu archiwum postów

### ISSUE THREAD

**Issue by ad-m** [ad-m/mc-theme#10]
http://localhost:8080/posts/ i http://localhost:8080/posts/ zawiera ``home.php`` z tymi samymi treściami. Tymczasem ``/posts`` powinno zawierać normalny wykaz,  a ``/`` zawierać przyjazny wykaz.

**Comment by ad-m** [comment]
Te urle to wynikają chyba z ``wp server``. Natomiast jest coś nie tak i pewnie istotną ilość czasu poświęcę jeżeli będę to analizował samemu.

**Comment by mik-laj** [comment]
Nie ma archiwum tylko dla wpisów w Wordpressie z tego co pamietam. Trzeba będzie sprawdzić routing, a potem dopisać, jeśli nie ma routingu.
