### ISSUE TITLE
Zwięzłe dodanie etykiet do listów nawigacyjnych postów

### ISSUE THREAD

**Issue by ad-m** [ad-m/mc-theme#5]
Jak to zrobić zwięźle? Dziś w ``/template-parts/content.php`` jest to zapisane bez etykiet "Starsze wpisy" i "Nowsze wpisy".

![zaznaczenie_1135](https://user-images.githubusercontent.com/3618479/32561245-1d0242d0-c4ac-11e7-91ab-b7a1ff4266c7.png)

**Comment by mik-laj** [comment]
https://codex.wordpress.org/Function_Reference/get_next_post
https://codex.wordpress.org/Function_Reference/get_previous_post

**Comment by ad-m** [comment]
@mik-laj , znam to. Tego użyłem w ww. Myślałem, że jest coś lepszego.

**Comment by ad-m** [comment]
Zdefiniowałem własną funkcje.
