### ISSUE TITLE
Dodać add_editor_style

### ISSUE THREAD

**Issue by ad-m** [ad-m/mc-theme#8]
> RECOMMENDED: No reference to add_editor_style() was found in the theme. It is recommended that the theme implement editor styling, so as to make the editor content match the resulting post output in the theme, for a better user experience.

W jaki sposób bez zbytniego DRY wydzielić skutecznie to? Wydzielić do osobnego pliku, ,a potem SASS…Ale jak zachować wówczas czytelność?

**Comment by mik-laj** [comment]
Tutaj po prostu powinny trafić wszystkie znaczniki p, b, table I inne style. To powinieneś trzymać w osobnym pliku w SCSS, a więc łatwo będzie wydzielić i zaimportować osobno.

**Comment by ad-m** [comment]
See #16
